import UIKit

// https://projecteuler.net/archives
/**
 2. Even Fibonacci numbers
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

func fibonacci(numbers: Int) -> Int {
    
    // Fibonacci için ilk iki değer ataması:
    var number1 = 0, number2 = 1
    
    // Soruda istenen çift değerler toplamının değişkeni:
    var sumNumber: Int = 0
    
    // Fibonacci serisi için:
    for _ in 0..<numbers {
        let number = number1 + number2
        number1 = number2
        number2 = number
        
        // Serideki çift olanların toplam değişkeninde toplanması için:
        if number % 2 == 0 && number < 4000000 {
            sumNumber += number
        }
    }
    return sumNumber
}

print(fibonacci(numbers: 8))
